apiVersion: v1
kind: Service
metadata:
  name: reflections
  namespace: reflections
spec:
  selector:
    app: reflections
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
