apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-sql
  namespace: reflections
data:
  create-tables.sql: |
    DROP TABLE IF EXISTS reflections;
    CREATE TABLE reflections (
        id SERIAL PRIMARY KEY,
        title TEXT NOT NULL,
        tags TEXT[] NOT NULL,
        body TEXT NOT NULL,
        created_at BIGINT NOT NULL,
        updated_at BIGINT NOT NULL
    );
